spring:
  autoconfigure:
    exclude: []
  datasource:
    url: ${MYSQL_JDBC_URL:jdbc:mysql://localhost:3306/lockbench?serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

lockbench:
  thread-fixed:
    platform-concurrency: 200
    virtual-concurrency: 200
