spring:
  autoconfigure:
    exclude: []
  datasource:
    url: ${MYSQL_JDBC_URL:jdbc:mysql://localhost:13306/lockbench?serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
      minimum-idle: ${HIKARI_MIN_IDLE:10}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

lockbench:
  routing-datasource:
    enabled: ${ROUTING_DS_ENABLED:false}
    write-pool-size: ${ROUTING_DS_WRITE_POOL:10}
    read-pool-size: ${ROUTING_DS_READ_POOL:10}
  thread-fixed:
    platform-concurrency: 200
    virtual-concurrency: 200
